<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>aspnet-puckweb-8B7BB765-2872-4000-9CDA-54028AE0BC40</UserSecretsId>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <ANCMPreConfiguredForIIS>true</ANCMPreConfiguredForIIS>
    <IsPackable>true</IsPackable>
    <PackageId>PuckCMS</PackageId>
    <Version>1.0.0-beta0001</Version>
    <Authors>Simon Yohannes</Authors>
    <Company>Puck CMS</Company>
    <Product>Puck CMS</Product>
    <Description>asp.net core code first mvc CMS</Description>
    <Copyright>https://github.com/yohsii/puck-core/blob/master/LICENSE</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/yohsii/puck-core</PackageProjectUrl>
    <RepositoryUrl>https://github.com/yohsii/puck-core</RepositoryUrl>
    <PackageTags>CMS, MVC</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\*" />
    <Content Include="wwwroot\*" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.3.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
    <PackageReference Include="SixLabors.ImageSharp.Web" Version="3.1.4" />
    <PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.1.4" />
  </ItemGroup>

  <Target Name="CopyCustomContentOnPublish" AfterTargets="Publish">
    <ItemGroup>
      <Views Include="Views\**" />
      <EmailTemplates Include="App_Data\EmailTemplates\**" />
    </ItemGroup>
    <Copy SourceFiles="@(Views)" DestinationFolder="$(PublishDir)\Views\%(RecursiveDir)" />
    <Copy SourceFiles="@(EmailTemplates)" DestinationFolder="$(PublishDir)\App_Data\EmailTemplates\" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\core\core.csproj" />
  </ItemGroup>


  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="echo &quot;App Offline&quot; /a &gt; &quot;$(ProjectDir)app_offline.htm&quot;" />
  </Target>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(OS)' != 'Windows_NT'">
    <Exec Command="echo &quot;App Offline&quot; &gt; &quot;$(ProjectDir)app_offline.htm&quot;" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(OS)' == 'Windows_NT'">
    <Exec Command="del &quot;$(ProjectDir)app_offline.htm&quot;" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(OS)' != 'Windows_NT'">
    <Exec Command="rm -f &quot;$(ProjectDir)app_offline.htm&quot;" />
  </Target>

</Project>
